# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ibdatastream import ibdatastream_pb2 as ibdatastream_dot_ibdatastream__pb2


class IBDataStreamStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LookUp = channel.unary_unary(
        '/ibdatastream.IBDataStream/LookUp',
        request_serializer=ibdatastream_dot_ibdatastream__pb2.ContractLookup.SerializeToString,
        response_deserializer=ibdatastream_dot_ibdatastream__pb2.Contract.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/ibdatastream.IBDataStream/Subscribe',
        request_serializer=ibdatastream_dot_ibdatastream__pb2.Contract.SerializeToString,
        response_deserializer=ibdatastream_dot_ibdatastream__pb2.Ticker.FromString,
        )


class IBDataStreamServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def LookUp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IBDataStreamServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LookUp': grpc.unary_unary_rpc_method_handler(
          servicer.LookUp,
          request_deserializer=ibdatastream_dot_ibdatastream__pb2.ContractLookup.FromString,
          response_serializer=ibdatastream_dot_ibdatastream__pb2.Contract.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=ibdatastream_dot_ibdatastream__pb2.Contract.FromString,
          response_serializer=ibdatastream_dot_ibdatastream__pb2.Ticker.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ibdatastream.IBDataStream', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
