# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibdatastream/ibdatastream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ibdatastream/ibdatastream.proto',
  package='ibdatastream',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fibdatastream/ibdatastream.proto\x12\x0cibdatastream\"\xab\x04\n\x0e\x43ontractLookup\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12:\n\x07secType\x18\x02 \x01(\x0e\x32).ibdatastream.ContractLookup.SecurityType\x12$\n\x1clastTradeDateOrContractMonth\x18\x03 \x01(\t\x12\x0e\n\x06strike\x18\x04 \x01(\t\x12\x31\n\x05right\x18\x05 \x01(\x0e\x32\".ibdatastream.ContractLookup.Right\x12\x12\n\nmultiplier\x18\x06 \x01(\t\x12\x10\n\x08\x65xchange\x18\x07 \x01(\t\x12\x10\n\x08\x63urrency\x18\x08 \x01(\t\x12\x13\n\x0blocalSymbol\x18\t \x01(\t\x12\x17\n\x0fprimaryExchange\x18\n \x01(\t\x12\x14\n\x0ctradingClass\x18\x0b \x01(\t\x12\x16\n\x0eincludeExpired\x18\x0c \x01(\x08\"\xa8\x01\n\x0cSecurityType\x12\t\n\x05STOCK\x10\x00\x12\n\n\x06OPTION\x10\x01\x12\n\n\x06\x46UTURE\x10\x02\x12\t\n\x05INDEX\x10\x03\x12\x12\n\x0e\x46UTURES_OPTION\x10\x04\x12\x08\n\x04\x43\x41SH\x10\x05\x12\x07\n\x03\x43\x46\x44\x10\x06\x12\t\n\x05\x43OMBO\x10\x07\x12\x0b\n\x07WARRANT\x10\x08\x12\x08\n\x04\x42OND\x10\t\x12\r\n\tCOMMODITY\x10\n\x12\x08\n\x04NEWS\x10\x0b\x12\x08\n\x04\x46UND\x10\x0c\"%\n\x05Right\x12\t\n\x05UNSET\x10\x00\x12\x07\n\x03PUT\x10\x01\x12\x08\n\x04\x43\x41LL\x10\x02\"\x1e\n\x08\x43ontract\x12\x12\n\ncontractID\x18\x01 \x01(\x03\"o\n\x06Ticker\x12\x0b\n\x03\x61sk\x18\x01 \x01(\t\x12\x0f\n\x07\x61skSize\x18\x02 \x01(\x03\x12\x0b\n\x03\x62id\x18\x03 \x01(\t\x12\x0f\n\x07\x62idSize\x18\x04 \x01(\x03\x12\x0c\n\x04open\x18\x05 \x01(\t\x12\r\n\x05\x63lose\x18\x06 \x01(\t\x12\x0c\n\x04last\x18\x07 \x01(\t2\x8f\x01\n\x0cIBDataStream\x12@\n\x06LookUp\x12\x1c.ibdatastream.ContractLookup\x1a\x16.ibdatastream.Contract\"\x00\x12=\n\tSubscribe\x12\x16.ibdatastream.Contract\x1a\x14.ibdatastream.Ticker\"\x00\x30\x01\x62\x06proto3')
)



_CONTRACTLOOKUP_SECURITYTYPE = _descriptor.EnumDescriptor(
  name='SecurityType',
  full_name='ibdatastream.ContractLookup.SecurityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOCK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPTION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FUTURE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDEX', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FUTURES_OPTION', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CASH', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CFD', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMBO', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARRANT', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOND', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMODITY', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEWS', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FUND', index=12, number=12,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=398,
  serialized_end=566,
)
_sym_db.RegisterEnumDescriptor(_CONTRACTLOOKUP_SECURITYTYPE)

_CONTRACTLOOKUP_RIGHT = _descriptor.EnumDescriptor(
  name='Right',
  full_name='ibdatastream.ContractLookup.Right',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=568,
  serialized_end=605,
)
_sym_db.RegisterEnumDescriptor(_CONTRACTLOOKUP_RIGHT)


_CONTRACTLOOKUP = _descriptor.Descriptor(
  name='ContractLookup',
  full_name='ibdatastream.ContractLookup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='ibdatastream.ContractLookup.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secType', full_name='ibdatastream.ContractLookup.secType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastTradeDateOrContractMonth', full_name='ibdatastream.ContractLookup.lastTradeDateOrContractMonth', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strike', full_name='ibdatastream.ContractLookup.strike', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='ibdatastream.ContractLookup.right', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='ibdatastream.ContractLookup.multiplier', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='ibdatastream.ContractLookup.exchange', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='ibdatastream.ContractLookup.currency', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='localSymbol', full_name='ibdatastream.ContractLookup.localSymbol', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='primaryExchange', full_name='ibdatastream.ContractLookup.primaryExchange', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tradingClass', full_name='ibdatastream.ContractLookup.tradingClass', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='includeExpired', full_name='ibdatastream.ContractLookup.includeExpired', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTRACTLOOKUP_SECURITYTYPE,
    _CONTRACTLOOKUP_RIGHT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=605,
)


_CONTRACT = _descriptor.Descriptor(
  name='Contract',
  full_name='ibdatastream.Contract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contractID', full_name='ibdatastream.Contract.contractID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=637,
)


_TICKER = _descriptor.Descriptor(
  name='Ticker',
  full_name='ibdatastream.Ticker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ask', full_name='ibdatastream.Ticker.ask', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='askSize', full_name='ibdatastream.Ticker.askSize', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bid', full_name='ibdatastream.Ticker.bid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bidSize', full_name='ibdatastream.Ticker.bidSize', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open', full_name='ibdatastream.Ticker.open', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='ibdatastream.Ticker.close', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last', full_name='ibdatastream.Ticker.last', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=750,
)

_CONTRACTLOOKUP.fields_by_name['secType'].enum_type = _CONTRACTLOOKUP_SECURITYTYPE
_CONTRACTLOOKUP.fields_by_name['right'].enum_type = _CONTRACTLOOKUP_RIGHT
_CONTRACTLOOKUP_SECURITYTYPE.containing_type = _CONTRACTLOOKUP
_CONTRACTLOOKUP_RIGHT.containing_type = _CONTRACTLOOKUP
DESCRIPTOR.message_types_by_name['ContractLookup'] = _CONTRACTLOOKUP
DESCRIPTOR.message_types_by_name['Contract'] = _CONTRACT
DESCRIPTOR.message_types_by_name['Ticker'] = _TICKER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContractLookup = _reflection.GeneratedProtocolMessageType('ContractLookup', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACTLOOKUP,
  '__module__' : 'ibdatastream.ibdatastream_pb2'
  # @@protoc_insertion_point(class_scope:ibdatastream.ContractLookup)
  })
_sym_db.RegisterMessage(ContractLookup)

Contract = _reflection.GeneratedProtocolMessageType('Contract', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACT,
  '__module__' : 'ibdatastream.ibdatastream_pb2'
  # @@protoc_insertion_point(class_scope:ibdatastream.Contract)
  })
_sym_db.RegisterMessage(Contract)

Ticker = _reflection.GeneratedProtocolMessageType('Ticker', (_message.Message,), {
  'DESCRIPTOR' : _TICKER,
  '__module__' : 'ibdatastream.ibdatastream_pb2'
  # @@protoc_insertion_point(class_scope:ibdatastream.Ticker)
  })
_sym_db.RegisterMessage(Ticker)



_IBDATASTREAM = _descriptor.ServiceDescriptor(
  name='IBDataStream',
  full_name='ibdatastream.IBDataStream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=753,
  serialized_end=896,
  methods=[
  _descriptor.MethodDescriptor(
    name='LookUp',
    full_name='ibdatastream.IBDataStream.LookUp',
    index=0,
    containing_service=None,
    input_type=_CONTRACTLOOKUP,
    output_type=_CONTRACT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='ibdatastream.IBDataStream.Subscribe',
    index=1,
    containing_service=None,
    input_type=_CONTRACT,
    output_type=_TICKER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IBDATASTREAM)

DESCRIPTOR.services_by_name['IBDataStream'] = _IBDATASTREAM

# @@protoc_insertion_point(module_scope)
